### ISSUE TITLE
Edit README.me

### ISSUE THREAD

**Issue by Shadolio** [Shadolio/Sprint0Comp#3]
Create a README.md that contains:
a) Project Title (title of sprint) -> DONE
b) Getting Started (explanation of content in repo)
c) Authors (all team member’s ﬁrst name & last name & ID) -> DONE
d) About (contains details about each team member and purpose of repository);
e) Design (be creative :D)

**Comment by AyaWaleed7** [comment]
Done

**Comment by Shadolio** [comment]
Hatla2o branch esmoh "editREADME", you can check it and add to it @AyaWaleed7 @aelazizashraf
